SocialApp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('account.urls')),
    url(r'^post/', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_feed, name='post_feed'),
    url(r'^(?P<pk>[0-9]+)/$', views.post_detail,name='post_detail'),
   # url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^like/$', views.post_like, name='like'),
    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),

]

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

# Create your models here.

class Post(models.Model):
    status = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='posts/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='posts_liked',blank=True)
    class Meta:
        ordering = ('created',)
        index_together = (('id'),)

    def __str__(self):
        return self.status

    def get_absolute_url(self):
        return reverse('posts:post_detail',args=[self.id])

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

posts/forms.py
from .models import Post, Comment
from django import forms

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('status', 'image','description',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from .forms import CommentForm, PostForm
from django.shortcuts import redirect

# Create your views here.

def post_feed(request):
    posts = Post.objects.filter()
    posts = posts.filter()
    return render(request,'posts/feed.html',{'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post,pk=pk)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request,'posts/detail.html',{'post': post,'comments': comments,'comment_form': comment_form})

@login_required
@require_POST
def post_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')
    if post_id and action:
        try:
            post = Post.objects.get(id=post_id)
            if action == 'like':
                post.users_like.add(request.user)
            else:
                post.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'ko'})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.image = form.cleaned_data["image"]
            post.save()
            return redirect('posts:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'posts/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('posts:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'posts/post_edit.html', {'form': form})

posts/templates/posts/detail.html
{% extends "base.html" %}

{% load static %}

{% block title %} {{ post.status }}{% endblock %}

{% block content %}
  <h1 style="color:#BDFF00">Status Updated: {{ post.status }}</h1>
<h2> {{ post.description|linebreaks }}</h2>
      {% with total_likes=post.users_like.count users_like=post.users_like.all %}
    <div class="post-info">
      <div>
        <span class="count">
            <span class="total">{{ total_likes }}</span>
          like{{ total_likes|pluralize }}
        </span>
           <a  style="color :#00FF00" href="#" data-id="{{ post.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
      {% if request.user not in users_like %}
        Like
      {% else %}
        Unlike
      {% endif %}
    </a>
      </div>
              <a style="color :#FFFFFF" class="btn btn-default" href="{% url "posts:post_edit" pk=post.pk %}">post edit</a>


    </div>
    <div class="post-likes">
      {% for user in post.users_like.all %}
        <div>
          <img width="10%" src="{{ user.profile.photo.url }}">
          <p>{{ user.first_name }}</p>
        </div>
      {% empty %}
        Nobody likes this post yet.
      {% endfor %}
    </div>
  {% endwith %}
{% with comments.count as total_comments %}
  <h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
  </h2>
{% endwith %}
{% for comment in comments %}
  <div class="comment">
    <p class="info">
      Comment {{ forloop.counter }} by {{ comment.name }}
      {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
  </div>
{% empty %}
  <p>There are no comments yet.</p>
{% endfor %}
{% if new_comment %}
  <h2>Your comment has been added.</h2>
{% else %}
  <h2>Add a new comment</h2>
  <form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
  </form>
{% endif %}
{% endblock %}


{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "posts:like" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('a.like').data('action');

          // toggle data-action
          $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
          // toggle link text
          $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

          // update total likes
          var previous_likes = parseInt($('span.count .total').text());
          $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
        }
      }
    );
  });
{% endblock %}

posts/templates/posts/feed.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Posts Feeds
{% endblock %}

{% block content %}
  <div id="sidebar">
        <a style="color :#FFFFFF" href="{% url "posts:post_feed" %}">All</a>
             </div>
  <div id="main" class="post_feed">
    <h1 style="color:#00FF74">Posts Updates</h1>
    {% for post in posts %}
      <div class="item">
        <a style="color :#FFFFFF" href="{{ post.get_absolute_url }}">
          <img src="{% if post.image %}{{ post.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a style="color :#FFFFFF" href="{{ post.get_absolute_url }}">{{ post.status }}</a><br>
          {{ post.description }}
        </div>
    {% endfor %}
  </div>
{% endblock %}

posts/templates/posts/post_edit.html
{% extends 'base.html' %}

{% block content %}
    <h1 style="color:#FFF0F5">New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}